### PR TITLE
Remove Centos 6 from this Cookbook

### PR DESCRIPTION
**Pull request by TheREK3R**

### CODE REVIEW

**Comment by TheREK3R** [comment]
I removed c8 from the metadata as well because its not actually supported but left it in spec so that we can test to make sure it doesn't run on c8.

**Comment by TheREK3R** [comment]
I can change that back on request though

**Review by ramereth — APPROVED** [review]
Please do a major bump on `~`

**Comment by TheREK3R** [comment]
!bump major ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v2.0.0.  Have a nice day!

**Pull request merged**
